module BrickBreaker {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.media;

    opens breakout to javafx.fxml;
    exports breakout;
    opens breakout.assembly to javafx.graphics, javafx.fxml;
    exports breakout.assembly;
    opens breakout.configs to javafx.graphics, javafx.fxml;
    exports breakout.configs;
    opens breakout.container to javafx.graphics, javafx.fxml;
    exports breakout.container;
    opens breakout.core.audio to javafx.graphics, javafx.fxml;
    exports breakout.core.audio;
    opens breakout.core.configs to javafx.graphics, javafx.fxml;
    exports breakout.core.configs;
    opens breakout.core.container to javafx.graphics, javafx.fxml;
    exports breakout.core.container;
    opens breakout.core.contracts to javafx.graphics, javafx.fxml;
    exports breakout.core.contracts;
    opens breakout.core.controllers to javafx.graphics, javafx.fxml;
    exports breakout.core.controllers;
    opens breakout.core.database to javafx.graphics, javafx.fxml;
    exports breakout.core.database;
    opens breakout.core.effects to javafx.graphics, javafx.fxml;
    exports breakout.core.effects;
    opens breakout.core.entities to javafx.graphics, javafx.fxml;
    exports breakout.core.entities;
    opens breakout.core.file to javafx.graphics, javafx.fxml;
    exports breakout.core.file;
    opens breakout.core.imaging to javafx.graphics, javafx.fxml;
    exports breakout.core.imaging;
    opens breakout.core.logging to javafx.graphics, javafx.fxml;
    exports breakout.core.logging;
    opens breakout.core.routing to javafx.graphics, javafx.fxml;
    exports breakout.core.routing;
    opens breakout.core.screens to javafx.graphics, javafx.fxml;
    exports breakout.core.screens;
    opens breakout.core.skeletons to javafx.graphics, javafx.fxml;
    exports breakout.core.skeletons;
    opens breakout.core.utils to javafx.graphics, javafx.fxml;
    exports breakout.core.utils;
    opens breakout.entities to javafx.graphics, javafx.fxml;
    exports breakout.entities;
    opens breakout.helpers to javafx.graphics, javafx.fxml;
    exports breakout.helpers;
    opens breakout.screens to javafx.graphics, javafx.fxml;
    exports breakout.screens;
}